/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sciaps;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.text.MaskFormatter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author jchen
 */
public class HTTPConfigPanel extends javax.swing.JPanel {
    
    Logger logger_ = LoggerFactory.getLogger(HTTPConfigPanel.class);
    
    JDialog popupDisplay_;
    JFormattedTextField txtIPAddress_;
    
    /**
     * Creates new form HTTPConfigPanel
     */
    public HTTPConfigPanel() {
        initComponents();
        
        try {
            MaskFormatter formatter = new MaskFormatter("###.###.###.###");
            txtIPAddress_ = new JFormattedTextField(formatter);
        } catch (ParseException ex) {
            txtIPAddress_ = new JFormattedTextField();
        }
        txtIPAddress_.setFont(new Font("Tahoma", Font.BOLD, 14));
        txtIPAddress_.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtIPAddress_, gridBagConstraints);
        
        createPopupDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        btnSave_ = new javax.swing.JButton();
        btnCancel_ = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Enter IP Address of LIBZ (example: 10.98.100.80)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        add(jLabel1, gridBagConstraints);

        btnSave_.setText("SAVE");
        btnSave_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnSave_, gridBagConstraints);

        btnCancel_.setText("CANCEL");
        btnCancel_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnCancel_, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_ActionPerformed
        popupDisplay_.dispose();
    }//GEN-LAST:event_btnCancel_ActionPerformed

    private void btnSave_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_ActionPerformed
        Common.LIBZ_URL = "http://" + txtIPAddress_.getText();
        popupDisplay_.dispose();
    }//GEN-LAST:event_btnSave_ActionPerformed

    private void createPopupDisplay() {
        popupDisplay_ = new JDialog();
        popupDisplay_.setResizable(false);
        popupDisplay_.setTitle("LIBZ Connection Setting");
        popupDisplay_.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        popupDisplay_.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                    e.getWindow().dispose();
            }
        });
        popupDisplay_.add(this, java.awt.BorderLayout.CENTER);
        popupDisplay_.setSize(new Dimension(300, 150));
        popupDisplay_.setLocationRelativeTo(this);
    }

    public void showPopup() {
        popupDisplay_.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel_;
    private javax.swing.JButton btnSave_;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
