/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sciaps.view;

import static com.sciaps.utils.Util.validateZeroOrGreater;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author jchen
 */
public class AverageShotsSettingPanel extends javax.swing.JPanel {

    private final Logger logger_ = LoggerFactory.getLogger(AverageShotsSettingPanel.class);
    private int sampleRate_;
    private String avgShotName_;

    private JDialog popupDisplay_;

    /**
     * Creates new form HTTPConfigPanel
     */
    public AverageShotsSettingPanel() {
        initComponents();
        sampleRate_ = -1;
        avgShotName_ = "";

        createPopupDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        btnOK_ = new javax.swing.JButton();
        txtName_ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSampleRate_ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Enter Name For This Average:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jLabel1, gridBagConstraints);

        btnOK_.setText("OK");
        btnOK_.setMaximumSize(new java.awt.Dimension(77, 23));
        btnOK_.setMinimumSize(new java.awt.Dimension(77, 23));
        btnOK_.setPreferredSize(new java.awt.Dimension(77, 23));
        btnOK_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK_ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(btnOK_, gridBagConstraints);

        txtName_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtName_KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 4);
        add(txtName_, gridBagConstraints);

        jLabel2.setText("Enter Sample Rate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jLabel2, gridBagConstraints);

        txtSampleRate_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSampleRate_.setText("30");
        txtSampleRate_.setMaximumSize(new java.awt.Dimension(77, 21));
        txtSampleRate_.setMinimumSize(new java.awt.Dimension(77, 21));
        txtSampleRate_.setPreferredSize(new java.awt.Dimension(77, 21));
        txtSampleRate_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSampleRate_KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(txtSampleRate_, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Raster Setting");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 6, 0);
        add(jLabel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOK_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK_ActionPerformed

        if (validateData() && popupDisplay_ != null) {
            popupDisplay_.dispose();
        }

    }//GEN-LAST:event_btnOK_ActionPerformed

    private void txtSampleRate_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSampleRate_KeyReleased
        validateZeroOrGreater(txtSampleRate_);
    }//GEN-LAST:event_txtSampleRate_KeyReleased

    private void txtName_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName_KeyReleased
        avgShotName_ = txtName_.getText();
        if (avgShotName_.isEmpty()) {
            txtName_.setBackground(Color.red);
        } else {
            txtName_.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtName_KeyReleased

    private void createPopupDisplay() {
        popupDisplay_ = new JDialog();
        popupDisplay_.setResizable(false);
        popupDisplay_.setTitle("Create Average Shots Setting");
        popupDisplay_.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        popupDisplay_.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                e.getWindow().dispose();
            }
        });
        popupDisplay_.add(this, java.awt.BorderLayout.CENTER);
        popupDisplay_.setSize(new Dimension(300, 200));
        popupDisplay_.setLocationRelativeTo(this);
        popupDisplay_.setModal(true);
    }

    private boolean validateData() {
        boolean allGood = true;

        try {
            sampleRate_ = validateZeroOrGreater(txtSampleRate_);
            if (sampleRate_ < 1) {
                showErrorDialog("Sample rate must be greater than 0");
            }
            avgShotName_ = txtName_.getText();
            if (avgShotName_.isEmpty()) {
                showErrorDialog("Name field can not be blank.");
            }
        } catch (NumberFormatException ex) {
            allGood = false;
        }

        return allGood;
    }

    public void showPopup() {
        this.getRootPane().setDefaultButton(btnOK_);
        popupDisplay_.setVisible(true);
    }

    public void setAvgShotName(String name) {
        avgShotName_ = name;
        txtName_.setText(name);
    }

    public String getAvgShotName() {
        return avgShotName_;
    }

    public void setSampleRate(int sampleRate) {
        sampleRate_ = sampleRate;
        txtSampleRate_.setText(String.valueOf(sampleRate));
    }

    public int getSampleRate() {
        return sampleRate_;
    }

    private void showErrorDialog(String msg) {
        logger_.error(msg);
        JOptionPane.showMessageDialog(this, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtName_;
    private javax.swing.JTextField txtSampleRate_;
    // End of variables declaration//GEN-END:variables
}
